<a href="https://colab.research.google.com/github/yretrut/IIS/blob/main/2lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Лабораторная работа 2**

Обзор библиотек в Google Colaboratory


Рассмотрим основные библиотеки, набирающие популярность, для анализа данных с помощью средств Python.


Подключим библиотеку numpy. И решим с ее помощью ряд задач.

Пример 1:

Задать вектора а и b, найти из сумму.

In [1]:
import numpy as np
a = np.array([1, 2, 3])
b=np.array([10, 0.2, 3])
a+b

array([11. ,  2.2,  6. ])

Пример 2:

Массив b преобразовать в массив комплексных чисел.


In [6]:
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.complex)
b

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

Пример 3:

Создать числовую последовательность от 10 до 30 с шагом 5.


In [7]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

Пример 4:

Создать массив из 15 элементов. Развернуть его (первый становится последним).


In [8]:
Z = np.arange(15)
Z = Z[::-1]
Z

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

Пример 5:

Создать массив 10x10 со случайными значениями, найти минимум и максимум.


In [17]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
Zmin, Zmax

(0.005166775981547689, 0.9904897453967241)

Пример 6:

Создать случайный вектор размера 30 и найти среднее значение всех элементов.


In [18]:
Z = np.random.random(30)
m = Z.mean()
m

0.4967128543582797

Pandas - это высокоуровневая Python библиотека для анализа данных, построена она поверх более низкоуровневой библиотеки NumPy (написана на Си), что является большим плюсом в производительности. В экосистеме Python, Pandas является наиболее продвинутой и быстроразвивающейся библиотекой для обработки и анализа данных.

Пример 7:

Создать объект Series, вывести на экран.


In [19]:
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

DataFrame
Объект DataFrame лучше всего представлять себе в виде обычной таблицы и это правильно, ведь DataFrame является табличной структурой данных. В любой таблице всегда присутствуют строки и столбцы. Столбцами в объекте DataFrame выступают объекты Series, строки которых являются их непосредственными элементами.

DataFrame проще всего сконструировать на примере питоновского словаря:


In [20]:
df = pd.DataFrame({
     'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
     'population': [17.04, 143.5, 9.5, 45.5],
     'square': [2724902, 17125191, 207600, 603628]
 })
df

country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628

Чтобы убедиться, что столбец в DataFrame это Series, извлекаем любой:

In [21]:
df = pd.DataFrame({
     'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine'],
     'population': [17.04, 143.5, 9.5, 45.5],
     'square': [2724902, 17125191, 207600, 603628]
 })
df['country']

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

Самостоятельная работа:

1. Создать таблицу из 3 столбцов, 5 строк.

In [25]:
df = pd.DataFrame({
     'country': ['Kazakhstan', 'Russia', 'Belarus', 'Ukraine','USA','Canada'],
     'population': [17.04, 143.5, 9.5, 45.5, 344.6, 38.5],
     'square': [2724902, 17125191, 207600, 603628, 9855453, 9534244]
 })
df


country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600
3     Ukraine       45.50    603628
4         USA      344.60   9855453
5      Canada       38.50   9534244