<a href="https://colab.research.google.com/github/yretrut/IIS/blob/main/4lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Лабораторная работа 4**

**Построение нейросети. Часть 1**

Написание Python кода
Хоть мы и не будем использовать библиотеки с нейронными сетями, мы импортируем 4 метода из математической библиотеки numpy. А именно:

exp — экспоненцирование

array — создание матрицы

dot — перемножения матриц

random — генерация случайных чисел


In [ ]:
from numpy import exp, array, random, dot
training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = array([[0, 1, 1, 0]]).T

«.T» — функция транспонирования матриц. 

In [ ]:
# Подключаем необходимые библиотеки
from numpy import exp, array, random, dot

class NeuralNetwork():
    def __init__(self):
        # Заполните генератор случайных чисел, чтобы он генерировал одни и те 
        # же числа при каждом запуске программы
        random.seed(1)

        # Мы моделируем один нейрон с 3 входными подключениями и 1 выходным 
        # Мы назначаем случайные веса матрице 3 x 1 со значениями в диапазоне 
        # от -1 до 1 и средним значением 0.
   
        self.synaptic_weights = 2 * random.random((3, 1)) - 1

    # Сигмовидная функция, описывающая S-образную кривую.    
    # Мы передаем взвешенную сумму входных данных через эту функцию, чтобы 
    # нормализовать их от 0 до 1.
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    # Производная сигмовидной функции.
    # Это градиент сигмовидной кривой.
    # Это показывает, насколько мы уверены в существующем весе.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # Мы обучаем нейронную сеть методом проб и ошибок.
    # Каждый раз регулируя синаптические веса.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Передайем обучающий набор через нашу нейронную сеть (отдельный нейрон).
            output = self.think(training_set_inputs)

            # Вычислите ошибку (разницу между желаемым и прогнозируемым выходными данными).
            error = training_set_outputs - output

            # Умножьте ошибку на вход и снова на градиент сигмовидной кривой.
            # Это означает, что менее уверенные веса корректируются больше.
            # Это означает, что входные данные, которые равны нулю, не вызывают изменения весов.
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

            # Отрегулируйте веса.
            self.synaptic_weights += adjustment

    
    def think(self, inputs):
        # Передайте входные данные через нашу нейронную сеть (наш единственный нейрон).
        return self.__sigmoid(dot(inputs, self.synaptic_weights))

if __name__ == "__main__":

    # Инициализируйте нейронную сеть с одним нейроном.
    neural_network = NeuralNetwork()

    print ("Случайные начальные синаптические веса:")
    print (neural_network.synaptic_weights)

    # Обучающий набор. У нас есть 4 примера, каждый из которых состоит из 3 
    # входных значений и 1 выходного значения.
    training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = array([[0, 1, 1, 0]]).T

    # Обучите нейронную сеть с помощью обучающего набора.
    # Количество итераций - 10 000 раз 
    neural_network.train(training_set_inputs, training_set_outputs, 10000)

    print ("Новые синаптические веса после тренировки: ")
    print (neural_network.synaptic_weights)

    # Протестируйте нейронную сеть в новой ситуации.
    print ("Учитывая новую ситуацию [1, 0, 0] -> ?: ")
    print (neural_network.think(array([1, 0, 0])))


Случайные начальные синаптические веса:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Новые синаптические веса после тренировки: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
Учитывая новую ситуацию [1, 0, 0] -> ?: 
[0.99993704]


В искусственных нейронных сетях функция активации нейрона определяет выходной сигнал, который определяется входным сигналом или набором входных сигналов. Стандартная компьютерная микросхема может рассматриваться как цифровая сеть функций активации, которые могут принимать значения «ON» (1) или «OFF» (0) в зависимости от входа. Это похоже на поведение линейного перцептрона в нейронных сетях. Однако только нелинейные функции активации позволяют таким сетям решать нетривиальные задачи с использованием малого числа узлов. В искусственных нейронных сетях эта функция также называется передаточной функцией.

Используем Функцию активации th:

In [6]:
# Подключаем необходимые библиотеки
from numpy import exp, array, random, dot, log, sin, cos, tanh

class NeuralNetwork():
    def __init__(self):
        # Заполните генератор случайных чисел, чтобы он генерировал одни и те 
        # же числа при каждом запуске программы
        random.seed(1)

        # Мы моделируем один нейрон с 3 входными подключениями и 1 выходным 
        # Мы назначаем случайные веса матрице 3 x 1 со значениями в диапазоне 
        # от -1 до 1 и средним значением 0.
   
        self.synaptic_weights = 2 * random.random((3, 1)) - 1

    # Сигмовидная функция, описывающая S-образную кривую.    
    # Мы передаем взвешенную сумму входных данных через эту функцию, чтобы 
    # нормализовать их от 0 до 1.
    def th(self, x):
        return tanh(x)

    # Производная сигмовидной функции.
    # Это градиент сигмовидной кривой.
    # Это показывает, насколько мы уверены в существующем весе.
    def th_derivative(self, x):
        return 1 - tanh(x)**2

    # Мы обучаем нейронную сеть методом проб и ошибок.
    # Каждый раз регулируя синаптические веса.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Передайем обучающий набор через нашу нейронную сеть (отдельный нейрон).
            output = self.think(training_set_inputs)

            # Вычислите ошибку (разницу между желаемым и прогнозируемым выходными данными).
            error = training_set_outputs - output

            # Умножьте ошибку на вход и снова на градиент сигмовидной кривой.
            # Это означает, что менее уверенные веса корректируются больше.
            # Это означает, что входные данные, которые равны нулю, не вызывают изменения весов.
            adjustment = dot(training_set_inputs.T, error * self.th_derivative(output))

            # Отрегулируйте веса.
            self.synaptic_weights += adjustment

    
    def think(self, inputs):
        # Передайте входные данные через нашу нейронную сеть (наш единственный нейрон).
        return self.th(dot(inputs, self.synaptic_weights))

if __name__ == "__main__":

    # Инициализируйте нейронную сеть с одним нейроном.
    neural_network = NeuralNetwork()

    print ("Случайные начальные синаптические веса:")
    print (neural_network.synaptic_weights)

    # Обучающий набор. У нас есть 4 примера, каждый из которых состоит из 3 
    # входных значений и 1 выходного значения.
    training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = array([[0, 1, 1, 0]]).T

    # Обучите нейронную сеть с помощью обучающего набора.
    # Количество итераций - 10 000 раз 
    neural_network.train(training_set_inputs, training_set_outputs, 10000)

    print ("Новые синаптические веса после тренировки: ")
    print (neural_network.synaptic_weights)

    # Протестируйте нейронную сеть в новой ситуации.
    print ("Учитывая новую ситуацию [1, 0, 0] -> ?: ")
    print (neural_network.think(array([1, 0, 0])))

Случайные начальные синаптические веса:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Новые синаптические веса после тренировки: 
[[5.39428067]
 [0.19482422]
 [0.34317086]]
Учитывая новую ситуацию [1, 0, 0] -> ?: 
[0.99995873]


В строке 
neural_network.train(training_set_inputs, training_set_outputs, 10000)
заменим количество итераций на 1000, на 100.


In [7]:
# Подключаем необходимые библиотеки
from numpy import exp, array, random, dot, log, sin, cos, tanh

class NeuralNetwork():
    def __init__(self):
        # Заполните генератор случайных чисел, чтобы он генерировал одни и те 
        # же числа при каждом запуске программы
        random.seed(1)

        # Мы моделируем один нейрон с 3 входными подключениями и 1 выходным 
        # Мы назначаем случайные веса матрице 3 x 1 со значениями в диапазоне 
        # от -1 до 1 и средним значением 0.
   
        self.synaptic_weights = 2 * random.random((3, 1)) - 1

    # Сигмовидная функция, описывающая S-образную кривую.    
    # Мы передаем взвешенную сумму входных данных через эту функцию, чтобы 
    # нормализовать их от 0 до 1.
    def th(self, x):
        return tanh(x)

    # Производная сигмовидной функции.
    # Это градиент сигмовидной кривой.
    # Это показывает, насколько мы уверены в существующем весе.
    def th_derivative(self, x):
        return 1 - tanh(x)**2

    # Мы обучаем нейронную сеть методом проб и ошибок.
    # Каждый раз регулируя синаптические веса.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Передайем обучающий набор через нашу нейронную сеть (отдельный нейрон).
            output = self.think(training_set_inputs)

            # Вычислите ошибку (разницу между желаемым и прогнозируемым выходными данными).
            error = training_set_outputs - output

            # Умножьте ошибку на вход и снова на градиент сигмовидной кривой.
            # Это означает, что менее уверенные веса корректируются больше.
            # Это означает, что входные данные, которые равны нулю, не вызывают изменения весов.
            adjustment = dot(training_set_inputs.T, error * self.th_derivative(output))

            # Отрегулируйте веса.
            self.synaptic_weights += adjustment

    
    def think(self, inputs):
        # Передайте входные данные через нашу нейронную сеть (наш единственный нейрон).
        return self.th(dot(inputs, self.synaptic_weights))

if __name__ == "__main__":

    # Инициализируйте нейронную сеть с одним нейроном.
    neural_network = NeuralNetwork()

    print ("Случайные начальные синаптические веса:")
    print (neural_network.synaptic_weights)

    # Обучающий набор. У нас есть 4 примера, каждый из которых состоит из 3 
    # входных значений и 1 выходного значения.
    training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = array([[0, 1, 1, 0]]).T

    # Обучите нейронную сеть с помощью обучающего набора.
    # Количество итераций - 10 000 раз 
    neural_network.train(training_set_inputs, training_set_outputs, 100)

    print ("Новые синаптические веса после тренировки: ")
    print (neural_network.synaptic_weights)

    # Протестируйте нейронную сеть в новой ситуации.
    print ("Учитывая новую ситуацию [1, 0, 0] -> ?: ")
    print (neural_network.think(array([1, 0, 0])))

Случайные начальные синаптические веса:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Новые синаптические веса после тренировки: 
[[3.12419059]
 [0.20197157]
 [0.35018332]]
Учитывая новую ситуацию [1, 0, 0] -> ?: 
[0.9961403]
